package com.techcity.techcitysuite

import com.google.firebase.Timestamp

/**
 * Data class representing a complete Device Transaction document
 * Stored in Firebase under "device_transactions" collection
 * Each device sale creates exactly one document containing all transaction details
 */
data class DeviceTransaction(
    // Document Identification (auto-generated by Firebase)
    val id: String = "",

    // Date and Time Fields
    val date: String = "",                    // Format: "YYYY-MM-DD" for daily queries
    val month: String = "",                   // Format: "YYYY-MM" for monthly queries
    val year: String = "",                    // Format: "YYYY" for yearly queries
    val timestamp: Timestamp? = null,         // Firestore Timestamp for exact moment
    val dateSold: String = "",                // Format: "M/D/YYYY" for display
    val time: String = "",                    // Format: "HH:mm:ss"

    // User and Location (from App Settings)
    val user: String = "",
    val userLocation: String = "",
    val deviceId: String = "",                // Device ID from AppSettingsManager

    // Inventory Reference and Status Tracking
    val inventoryDocumentId: String = "",
    val originalStatus: String = "",          // Status before transaction
    val originalLastUpdated: String = "",     // lastUpdated before transaction
    val newStatus: String = "Sold",           // Always "Sold" for completed sales
    val newLastUpdated: String = "",          // Current date when transaction is saved

    // Device Identification
    val imei1: String = "",
    val imei2: String = "",
    val serialNumber: String = "",
    val identifierUsed: String = "",          // The identifier that was searched/matched

    // Device Details
    val deviceType: String = "",              // "Phone", "Tablet", "Laptop", "Printer"
    val manufacturer: String = "",
    val model: String = "",
    val ram: String = "",
    val storage: String = "",
    val color: String = "",

    // Pricing Information - Original (from inventory, for audit)
    val originalRetailPrice: Double = 0.0,
    val originalDealersPrice: Double = 0.0,

    // Pricing Information - Transaction (may differ due to promotions)
    val price: Double = 0.0,                  // Actual selling price entered by user
    val discountAmount: Double = 0.0,         // Discount in peso amount
    val discountPercent: Double = 0.0,        // Calculated: (discountAmount / price) * 100
    val finalPrice: Double = 0.0,             // Calculated: price - discountAmount

    // Transaction Type
    val transactionType: String = "",         // "Cash Transaction", "Home Credit Transaction", etc.

    // Payment Details (only ONE of these will be populated based on transactionType)
    val cashPayment: CashPaymentDetails? = null,
    val homeCreditPayment: HomeCreditPaymentDetails? = null,
    val skyroPayment: SkyroPaymentDetails? = null,
    val inHouseInstallment: InHouseInstallmentDetails? = null,

    // Account Settings Snapshot (captured at time of transaction for audit trail)
    val accountSettingsSnapshot: AccountSettingsSnapshot = AccountSettingsSnapshot(),

    // Transaction Status
    val status: String = "completed",         // "completed", "void", "returned"

    // Void Information (null if not voided)
    val voidReason: String? = null,
    val voidedAt: Timestamp? = null,
    val voidedBy: String? = null,

    // Audit Trail
    val createdBy: String = "",
    val createdAt: Timestamp? = null,         // Server timestamp
    val updatedBy: String? = null,
    val updatedAt: Timestamp? = null,

    // Notes
    val notes: String = ""
) {
    // No-argument constructor required for Firestore
    constructor() : this("")
}