package com.techcity.techcitysuite

import com.google.firebase.Timestamp

/**
 * Data class representing a Service Transaction document
 * Stored in Firebase under "service_transactions" collection
 *
 * Service types include:
 * - Cash In
 * - Cash Out
 * - Mobile Loading Service
 * - Skyro Payment
 * - Home Credit Payment
 * - Misc Payment
 *
 * LEDGER DESIGN:
 * Each transaction contains embedded ledger entry information.
 * This allows the Ledger View to be built directly from transaction documents
 * without needing a separate ledger collection.
 *
 * Double-Entry Bookkeeping:
 * - Every transaction has a CREDIT entry (money coming in)
 * - Every transaction has a DEBIT entry (money going out)
 * - Credit and Debit amounts may differ (e.g., fee scenarios)
 *
 * Example - Cash In ₱1,000 to GCash with ₱15 fee (Add Fee):
 *   Credit: Cash ₱1,015 (customer pays)
 *   Debit: GCash ₱1,000 (transferred amount)
 *
 * Example - Mobile Loading ₱100 from GCash with ₱5 fee (Add Fee):
 *   Credit: Cash ₱105 (customer pays)
 *   Debit: GCash ₱100 (load amount sent)
 */
data class ServiceTransaction(
    // =========================================================================
    // DOCUMENT IDENTIFICATION
    // =========================================================================
    val id: String = "",                      // Auto-generated by Firebase

    // =========================================================================
    // DATE AND TIME FIELDS
    // =========================================================================
    val date: String = "",                    // Format: "yyyy-MM-dd" for daily queries
    val month: String = "",                   // Format: "yyyy-MM" for monthly queries
    val year: String = "",                    // Format: "yyyy" for yearly queries
    val timestamp: Timestamp? = null,         // Firestore server timestamp for exact moment
    val dateSaved: String = "",               // Format: "M/d/yyyy" for display
    val time: String = "",                    // Format: "HH:mm:ss" (Philippine time)

    // =========================================================================
    // USER AND DEVICE IDENTIFICATION
    // =========================================================================
    val user: String = "",                    // User name from AppSettings
    val userLocation: String = "",            // Store location from AppSettings
    val deviceId: String = "",                // Android device ID

    // =========================================================================
    // TRANSACTION DETAILS
    // =========================================================================
    val transactionType: String = "",         // "Cash In", "Cash Out", "Mobile Loading Service",
    // "Skyro Payment", "Home Credit Payment", "Misc Payment"

    val amount: Double = 0.0,                 // Base amount entered by user
    val fee: Double = 0.0,                    // Transaction fee
    val feeOption: String = "",               // "Add Fee", "Deduct Fee", "Free"
    val customerPays: Double = 0.0,           // Total amount customer pays
    val customerReceives: Double = 0.0,       // Amount customer receives (after fee if applicable)

    // =========================================================================
    // SOURCE AND PAYMENT DETAILS
    // =========================================================================
    val sourceOfFunds: String = "",           // Dropdown selection:
    // Cash In: "GCash", "PayMaya", "Others" (Transfer To)
    // Cash Out: "GCash", "PayMaya", "Others" (Source of Funds)
    // Mobile Loading: "GCash", "Reloader SIM" (Load Source)
    // Skyro/HC: "GCash", "PayMaya", "Others" (Payment Method)
    // Misc Payment: "Cash", "GCash", "PayMaya", "Others"

    val paidWith: String? = null,             // If checkbox checked: "Cash", "GCash", "PayMaya", "Others"
    val isPaidWithChecked: Boolean = false,   // Whether the "Paid with" checkbox was checked

    // =========================================================================
    // EMBEDDED LEDGER ENTRIES (Double-Entry Bookkeeping)
    // =========================================================================
    // CREDIT ENTRY - Money coming INTO a ledger
    val creditLedgerType: String = "",        // "Cash", "GCash", "PayMaya", "Others"
    val creditAmount: Double = 0.0,           // Amount credited to this ledger
    val creditDescription: String = "",       // Description for ledger display

    // DEBIT ENTRY - Money going OUT OF a ledger
    val debitLedgerType: String = "",         // "Cash", "GCash", "PayMaya", "Others"
    val debitAmount: Double = 0.0,            // Amount debited from this ledger
    val debitDescription: String = "",        // Description for ledger display

    // =========================================================================
    // TRANSACTION NUMBERING
    // =========================================================================
    val ledgerTransactionNumber: Int = 0,     // Sequential number from LedgerManager (legacy)
    val sortOrder: Int = 0,                   // Custom sort order for drag-and-drop in list view

    // =========================================================================
    // STATUS AND NOTES
    // =========================================================================
    val status: String = "completed",         // "completed", "void"
    val notes: String = "",                   // User-entered notes

    // =========================================================================
    // AUDIT TRAIL
    // =========================================================================
    val createdBy: String = "",               // User who created the transaction
    val createdAt: Timestamp? = null          // Server timestamp when created
) {
    // No-argument constructor required for Firestore deserialization
    constructor() : this("")

    companion object {
        /**
         * Ledger type constants for consistency
         */
        const val LEDGER_CASH = "Cash"
        const val LEDGER_GCASH = "GCash"
        const val LEDGER_PAYMAYA = "PayMaya"
        const val LEDGER_OTHERS = "Others"

        /**
         * Transaction type constants
         */
        const val TYPE_CASH_IN = "Cash In"
        const val TYPE_CASH_OUT = "Cash Out"
        const val TYPE_MOBILE_LOADING = "Mobile Loading Service"
        const val TYPE_SKYRO_PAYMENT = "Skyro Payment"
        const val TYPE_HOME_CREDIT_PAYMENT = "Home Credit Payment"
        const val TYPE_MISC_PAYMENT = "Misc Payment"

        /**
         * Fee option constants
         */
        const val FEE_ADD = "Add Fee"
        const val FEE_DEDUCT = "Deduct Fee"
        const val FEE_FREE = "Free"

        /**
         * Status constants
         */
        const val STATUS_COMPLETED = "completed"
        const val STATUS_VOID = "void"
    }
}